config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_DOCKERFORCEPUSH: enabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - hadolint --ignore SC2046 --ignore DL3002 --ignore DL3059 --ignore SC2086
          --ignore DL3008 --ignore DL3003 --ignore DL4006 --ignore SC2028 master-image/Dockerfile
        - hadolint --ignore SC2046 --ignore DL3059 --ignore SC2086 --ignore DL3008
          worker-image/Dockerfile
        container: scipion-hadolint
timeout: 600
